### ISSUE TITLE
Node.js v18.x build error

### ISSUE THREAD

**Issue by rhastie** [sony/nmos-js#83]
I'm currently using Node.js v16 LTS for production but testing Node.js v18. I am seeing build errors under Node.js v18.x...  Any suggestions welcome?

```
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-admin > connected-react-router@6.8.0" has unmet peer dependency "immutable@^3.8.1 || ^4.0.0-rc.1".
warning "react-admin > connected-react-router@6.8.0" has unmet peer dependency "history@^4.7.2".
warning "react-admin > connected-react-router@6.8.0" has incorrect peer dependency "react@^16.4.0".
warning "react-admin > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 129.12s.
yarn run v1.22.15
$ react-scripts build
node:internal/modules/cjs/loader:489
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /home/nmos-js/Development/node_modules/postcss-safe-parser/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:483:36)
    at Module._findPath (node:internal/modules/cjs/loader:523:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/nmos-js/Development/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.0.0
error Command failed with exit code 1.
```

**Comment by peterbrightwell** [comment]
@rhastie @garethsb did you get this working?   The postcss issue suggested `npm install postcss` but that's not working for me with Node 19.

**Comment by peterbrightwell** [comment]
Nor with node.js v18.12.1, using corepack and yarn (and `yarn add postcss`)

**Comment by peterbrightwell** [comment]
In the meantime I've downgraded to v16.18.1 (with corepack 0.14.1 and yarn 3.2.4) and `yarn start` runs

**Comment by garethsb** [comment]
Hey, @jonathan-r-thorpe, any thoughts on supporting Node v18+ ?

**Comment by rhastie** [comment]
So I've just checked the same issue is happening with Node v20.x as well. Is there anything we can do as it potentially just looks like a new syntax issue with later versions of Node

**Comment by jonathan-r-thorpe** [comment]
@garethsb in the short term pragmatically updating incompatible library versions *just enough* to mitigate this issue, but not so much that it requires a complete overhaul of the codebase.  I'll schedule some time next week to take a look.

**Comment by ruurdadema** [comment]
Any updates on this? I'm running into this issue which is preventing me from building the project.

Building docker image:

```
nmos-js % docker build -t nmos-js Development
[+] Building 590.8s (14/15)                                                                                                                                                                                         docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                                                0.0s
 => => transferring dockerfile: 281B                                                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                                                                                                                                     3.3s
 => [internal] load metadata for docker.io/library/node:latest                                                                                                                                                                      3.4s
 => [auth] library/nginx:pull token for registry-1.docker.io                                                                                                                                                                        0.0s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                   0.0s
 => => transferring context: 59B                                                                                                                                                                                                    0.0s
 => [build 1/6] FROM docker.io/library/node:latest@sha256:c332080545f1de96deb1c407e6fbe9a7bc2be3645e127845fdcce57a7af3cf56                                                                                                        445.4s
 => => resolve docker.io/library/node:latest@sha256:c332080545f1de96deb1c407e6fbe9a7bc2be3645e127845fdcce57a7af3cf56                                                                                                                0.0s
 => => sha256:c332080545f1de96deb1c407e6fbe9a7bc2be3645e127845fdcce57a7af3cf56 5.14kB / 5.14kB                                                                                                                                      0.0s
 => => sha256:fdf08fb5c1dc9b5039fdc6feeeec01bfaf5ba17c6b4fe0104dfb496f0f2f62e4 6.43kB / 6.43kB                                                                                                                                      0.0s
 => => sha256:280bbe393e788ced1dcb033580604b24de083601624337be66b3ec31781dae40 23.55MB / 23.55MB                                                                                                                                   40.4s
 => => sha256:1f4f297e4f699ae0f384d5cc1ea42065f58a115aa0a634d427cbb186f91cb4d0 64.36MB / 64.36MB                                                                                                                                  115.5s
 => => sha256:02b5c3538863870f2b32651bd09b26736fcf99014bc30002eb080086d76946d7 2.50kB / 2.50kB                                                                                                                                      0.0s
 => => sha256:1a12b4ea7c0ce04aa0e98be0a8c9942162bac71426f734fe6d3bf988bc9e2627 48.33MB / 48.33MB                                                                                                                                   80.1s
 => => sha256:b58ee5cb7152015437e4a9b3066ae9e25a26a3bef6617d0b7f25368511c2d954 202.76MB / 202.76MB                                                                                                                                438.3s
 => => extracting sha256:1a12b4ea7c0ce04aa0e98be0a8c9942162bac71426f734fe6d3bf988bc9e2627                                                                                                                                           1.8s
 => => sha256:4c4eb3d16508b3a9f96749a2d76662a53ec4f171cfaeb7732dc6efb0f9cdbb77 3.33kB / 3.33kB                                                                                                                                     80.6s
 => => sha256:b366fb27ec95a8ae9db95196e404529867b982018978e62cb39e11e4d4bc2d02 57.88MB / 57.88MB                                                                                                                                  172.3s
 => => extracting sha256:280bbe393e788ced1dcb033580604b24de083601624337be66b3ec31781dae40                                                                                                                                           0.5s
 => => extracting sha256:1f4f297e4f699ae0f384d5cc1ea42065f58a115aa0a634d427cbb186f91cb4d0                                                                                                                                           2.1s
 => => sha256:0742833e3d500ed709bc474baa180ddca3cf3f2d5f81b428157ed6aaef5c1058 1.25MB / 1.25MB                                                                                                                                    118.9s
 => => sha256:a37f44bbd5f690b4757680f197c6a530aec0452572cf859f8b116491097b3a64 447B / 447B                                                                                                                                        119.1s
 => => extracting sha256:b58ee5cb7152015437e4a9b3066ae9e25a26a3bef6617d0b7f25368511c2d954                                                                                                                                           4.7s
 => => extracting sha256:4c4eb3d16508b3a9f96749a2d76662a53ec4f171cfaeb7732dc6efb0f9cdbb77                                                                                                                                           0.0s
 => => extracting sha256:b366fb27ec95a8ae9db95196e404529867b982018978e62cb39e11e4d4bc2d02                                                                                                                                           1.8s
 => => extracting sha256:0742833e3d500ed709bc474baa180ddca3cf3f2d5f81b428157ed6aaef5c1058                                                                                                                                           0.0s
 => => extracting sha256:a37f44bbd5f690b4757680f197c6a530aec0452572cf859f8b116491097b3a64                                                                                                                                           0.0s
 => [stage-1 1/2] FROM docker.io/library/nginx:alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10                                                                                                     158.2s
 => => resolve docker.io/library/nginx:alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10                                                                                                               0.0s
 => => sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10 10.33kB / 10.33kB                                                                                                                                    0.0s
 => => sha256:63ffc0d1f14e4082b832c6a42e606e9a0384a526f16ddd720af7c1f018f2f7c4 2.50kB / 2.50kB                                                                                                                                      0.0s
 => => sha256:96868d9fa38f469a86d2f25787e43ee9ad330339d30be260aa9f5a338bb03751 10.80kB / 10.80kB                                                                                                                                    0.0s
 => => sha256:6e771e15690e2fabf2332d3a3b744495411d6e0b00b2aea64419b58b0066cf81 3.99MB / 3.99MB                                                                                                                                    126.9s
 => => extracting sha256:6e771e15690e2fabf2332d3a3b744495411d6e0b00b2aea64419b58b0066cf81                                                                                                                                           0.1s
 => => sha256:c60e446e49a0b607fd79968afdc54cedce67644990a3930925add6caf577779d 1.79MB / 1.79MB                                                                                                                                    129.8s
 => => extracting sha256:c60e446e49a0b607fd79968afdc54cedce67644990a3930925add6caf577779d                                                                                                                                           0.0s
 => => sha256:e6557c42ebeaea010d8a8883fdacdc5a17dea1221416d0d980e206dd42dc7e29 627B / 627B                                                                                                                                        129.9s
 => => extracting sha256:e6557c42ebeaea010d8a8883fdacdc5a17dea1221416d0d980e206dd42dc7e29                                                                                                                                           0.0s
 => => sha256:d3282d7e6b7633cf153dce0ca1c72b6ea574edb0b34351f848fb16b7d13c851f 957B / 957B                                                                                                                                        130.1s
 => => extracting sha256:d3282d7e6b7633cf153dce0ca1c72b6ea574edb0b34351f848fb16b7d13c851f                                                                                                                                           0.0s
 => => sha256:a4ce1202d74643d4e4ce15787afc2402a18802e3d7bfd0f6bf60c912b57eec1f 405B / 405B                                                                                                                                        130.3s
 => => extracting sha256:a4ce1202d74643d4e4ce15787afc2402a18802e3d7bfd0f6bf60c912b57eec1f                                                                                                                                           0.0s
 => => sha256:1ab010a063387e697fc32bb43022532c0e275d2e51fb65c2ac541e082e610a33 1.21kB / 1.21kB                                                                                                                                    130.5s
 => => extracting sha256:1ab010a063387e697fc32bb43022532c0e275d2e51fb65c2ac541e082e610a33                                                                                                                                           0.0s
 => => sha256:37aca2470cdaf48d251d9308c09dc8735b45ebcbefada46537c9989991b3fe6d 1.40kB / 1.40kB                                                                                                                                    131.0s
 => => extracting sha256:37aca2470cdaf48d251d9308c09dc8735b45ebcbefada46537c9989991b3fe6d                                                                                                                                           0.0s
 => => sha256:9994ea1088e3f1d0eb3dea855f32e7e63742b2644c8611c124ba81bc3453047e 16.03MB / 16.03MB                                                                                                                                  157.8s
 => => extracting sha256:9994ea1088e3f1d0eb3dea855f32e7e63742b2644c8611c124ba81bc3453047e                                                                                                                                           0.3s
 => [internal] load build context                                                                                                                                                                                                   0.0s
 => => transferring context: 1.14MB                                                                                                                                                                                                 0.0s
 => [build 2/6] WORKDIR /usr/src/app                                                                                                                                                                                                0.3s
 => [build 3/6] COPY package.json yarn.lock ./                                                                                                                                                                                      0.0s
 => [build 4/6] RUN yarn                                                                                                                                                                                                          141.1s
 => [build 5/6] COPY . ./                                                                                                                                                                                                           0.0s
 => ERROR [build 6/6] RUN yarn build                                                                                                                                                                                                0.5s
------
 > [build 6/6] RUN yarn build:
0.171 yarn run v1.22.22
0.178 (node:7) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
0.178 (Use `node --trace-deprecation ...` to show where the warning was created)
0.186 $ react-scripts build
0.451 node:internal/modules/cjs/loader:668
0.451       throw e;
0.451       ^
0.451
0.451 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /usr/src/app/node_modules/postcss-safe-parser/node_modules/postcss/package.json
0.451     at exportsNotFound (node:internal/modules/esm/resolve:313:10)
0.451     at packageExportsResolve (node:internal/modules/esm/resolve:660:9)
0.451     at resolveExports (node:internal/modules/cjs/loader:661:36)
0.451     at Module._findPath (node:internal/modules/cjs/loader:753:31)
0.451     at Module._resolveFilename (node:internal/modules/cjs/loader:1391:27)
0.451     at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
0.451     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
0.451     at Module._load (node:internal/modules/cjs/loader:1215:37)
0.451     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
0.451     at wrapModuleLoad (node:internal/modules/cjs/loader:235:24) {
0.451   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
0.451 }
0.451
0.451 Node.js v24.1.0
0.463 error Command failed with exit code 1.
0.463 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:6
--------------------
   4 |     RUN yarn
   5 |     COPY . ./
   6 | >>> RUN yarn build
   7 |
   8 |     FROM nginx:alpine
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/tdzyy63nz4ksnckd76q4hyr07
```

Building locally:

```
Development % yarn start
yarn run v1.22.22
warning ../../../../package.json: No license field
$ react-scripts start
node:internal/modules/cjs/loader:643
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /Users/ruurd/dev/libraries/nmos-js/Development/node_modules/postcss-safe-parser/node_modules/postcss/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:322:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:670:9)
    at resolveExports (node:internal/modules/cjs/loader:636:36)
    at Module._findPath (node:internal/modules/cjs/loader:716:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1198:27)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at Object.<anonymous> (/Users/ruurd/dev/libraries/nmos-js/Development/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1529:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.19.2
error Command failed with exit code 1.
``` 

When switching to node 16 I get:

``` 
Development % yarn start
/Users/ruurd/.nvm/versions/node/v16.20.2/lib/node_modules/corepack/dist/lib/corepack.cjs:22184
  return !URL.canParse(descriptor.range);
              ^

TypeError: URL.canParse is not a function
    at isSupportedPackageManagerDescriptor (/Users/ruurd/.nvm/versions/node/v16.20.2/lib/node_modules/corepack/dist/lib/corepack.cjs:22184:15)
    at Engine.resolveDescriptor (/Users/ruurd/.nvm/versions/node/v16.20.2/lib/node_modules/corepack/dist/lib/corepack.cjs:22966:10)
    at Engine.executePackageManagerRequest (/Users/ruurd/.nvm/versions/node/v16.20.2/lib/node_modules/corepack/dist/lib/corepack.cjs:22959:33)
    at async Object.runMain (/Users/ruurd/.nvm/versions/node/v16.20.2/lib/node_modules/corepack/dist/lib/corepack.cjs:23660:7)
``

**Comment by jonathan-r-thorpe** [comment]
Code base was updated for recent versions of NodeJS and we're now at Node 22.
